### ISSUE TITLE
Compatible with dominos?

### ISSUE THREAD

**Issue by Xizlol** [jwldnr/jButtonFlash#3]
Hi. Always loved snowfallkeypress back in the ERA during wotlk private servers, molten, AT and such.
Sticking around on live (retail now) any updates about this addon working together with Dominos?

**Comment by woldner** [comment]
Hi Xiz, thanks for the request.

This is definitely something that I would like to do, but I've not been able to fit this into my daily life. I would gladly accept an PR that fixes this issue, but in absence of such a PR, I'd have to ask you to wait until I've got time to fix this in my spare time..

Thanks for your understanding

**Comment by woldner** [comment]
Version 2.1 add support for Domino's on retail!
